#!/bin/bash

norm=False

if $norm; then
    bedtools genomecov -bg -scale .00925028305866159504 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/SMC1-2_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/SMC1-2_bowtie2.fragments.normalized.bedgraph
    bedtools genomecov -bg -scale .01066704214655022523 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/Gro-1_bowtie2.fragments.normalized.bedgraph
    bedtools genomecov -bg -scale .03720376502102012723 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-2_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/Gro-2_bowtie2.fragments.normalized.bedgraph
    bedtools genomecov -bg -scale .00249771583886535763 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/CtBP-1_bowtie2.fragments.normalized.bedgraph
    bedtools genomecov -bg -scale .00375769905565265032 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/CtBP-2_bowtie2.fragments.normalized.bedgraph
    bedtools genomecov -bg -scale .02448387981353077134 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/FLAG-1_bowtie2.fragments.normalized.bedgraph
    bedtools genomecov -bg -scale .01437671891645544870 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/FLAG-2_bowtie2.fragments.normalized.bedgraph
    bedtools genomecov -bg -scale .00052490214511759645 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/Ubx-1_bowtie2.fragments.normalized.bedgraph
    bedtools genomecov -bg -scale .00251465920584044688 -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/Ubx-2_bowtie2.fragments.normalized.bedgraph
else
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/SMC1-2_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/SMC1-2_bowtie2.fragments.bedgraph
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/Gro-1_bowtie2.fragments.bedgraph
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-2_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/Gro-2_bowtie2.fragments.bedgraph
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/CtBP-1_bowtie2.fragments.bedgraph
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/CtBP-2_bowtie2.fragments.bedgraph
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/FLAG-1_bowtie2.fragments.bedgraph
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/FLAG-2_bowtie2.fragments.bedgraph
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/Ubx-1_bowtie2.fragments.bedgraph
    bedtools genomecov -bg -i /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bed/Gro-1_bowtie2.fragments.bed -g /Users/matthewlee/Desktop/Columbia/Sequencing/Drosophila_melanogaster_UCSC_dm6/Drosophila_melanogaster/UCSC/dm6/dm6.chrom.sizes.txt > /Users/matthewlee/Desktop/Columbia/Sequencing/alignment/bedgraph/Ubx-2_bowtie2.fragments.bedgraph
fi